### ISSUE TITLE
Help running the docker container

### ISSUE THREAD

**Issue by kastork** [jupyterhub/configurable-http-proxy#101]
Requesting just a little bit of documentation for use of the Docker container.

I've tried running the docker container like so:

```
docker run -it -p 80:8000 -p 8001:8001 jupyterhub/configurable-http-proxy --default-target http://localhost:8080
```

But the server running on port 8080 doesn't receive requests, and the proxy reports a refused connection as so:

```
06:26:23.522 - error: [ConfigProxy] Proxy error:  Error: connect ECONNREFUSED 127.0.0.1:8080
    at Object.exports._errnoException (util.js:893:11)
    at exports._exceptionWithHostPort (util.js:916:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1075:14)
```

I've confirmed I can reach the server on port 8080 directly.

I can fix this by changing the default route to the machine's actual IP.

```
docker run -it -p 80:8000 -p 8001:8001 jupyterhub/configurable-http-proxy --default-target http://10.0.0.7:8080
```

If I try to reach the API, I can do a GET, but it doesn't report the default route.

```
› curl http://localhost:8001/api/routes
curl: (52) Empty reply from server
```

POSTing a new route does not work...

```
curl -i -X POST http://localhost:8001/api/routes -d '{"/foo":{"target":"http://localhost:8082"}}'

curl: (52) Empty reply from server

curl http://localhost:8001/api/routes
curl: (52) Empty reply from server
```

I've also tried deriving a container and exposing the 8001 port explicitly, but I don't see any difference in behavior.

**Comment by minrk** [comment]
The `--default-target http://localhost:8080` means that the proxy will forward requests to localhost:8080 *inside the container*, which I'm guessing isn't what you want. You will need to pass the host of the target *as seen from the proxy's container*, such as `--default-target http://other-container:8080`. I see you have discovered this by passing the machine's actual IP.

Assuming you are on linux and not macOS or Windows, you can use `--net=host` to put the proxy's networking into the host context, which should cause `localhost` to resolve how you expect both inside and outside the proxy.

The second piece is the API interface. This listens only on localhost by default (as above, this is resolved in the container, not on the host), which isn't what docker exposes when you pass a `-p` argument. To expose the API on the docker URL, you will need to add `--api-ip=0.0.0.0` to your docker command. As you've discovered, listening only on localhost doesn't make a whole lot of sense when CHP is run in a container, so we should probably change make `--api-ip=0.0.0.0` the default behavior of the container.

**Comment by kastork** [comment]
@minrk Thanks for the details.  I'll try to do some more experimenting later this week.
