### ISSUE TITLE
Reverse proxy with subpath

### ISSUE THREAD

**Issue by jri-sp** [jupyterhub/configurable-http-proxy#112]
Hi,

I'm following this guide: https://github.com/jupyter/tmpnb

I've set up a local installation for a workshop, which works as expected.

Now I need to reverse proxy this installation with my Apache front web server (to share public URL to users)
I need to reverse proxy like this:
`https://my.domain/jupyterworkshop/ ----> http://localserver:8000/`

Which implies final urls like `https://my.domain/jupyterworkshop/user/XnXqexlEzX8f` for example.

But when I'm doing my ProxyPath rule, it always redirect to `https://my.domain/spawn/jupyterworkshop/`

Is there a way to specify a subpath to jupyter tmpnb ?

I don't know if I'm clear, ask me questions if needed.

BTW thanks for all your work on Jupyter!

**Comment by minrk** [comment]
I don't believe that tmpnb supports a base url yet, but it could be added.

**Comment by willingc** [comment]
This issue was moved to jupyter/tmpnb#281
