### ISSUE TITLE
Need help - Cannot make a simple reverse proxy work

### ISSUE THREAD

**Issue by ecarlotti** [jupyterhub/configurable-http-proxy#119]
Guys,

First of all let me thank you for this, as it seems to have exactly what I was looking for to a project of mine that requires me to dynamically create reverse proxy routes.

What I'm trying to accomplish here is to define a route that simply and transparently "points" to some other address. What I did so far:

1) Started CHP using: `configurable-http-proxy --default-target=http://localhost:3000 --insecure --log-level debug`
2) Defined a route using: `curl -H "Content-Type: application/json" -X "POST" -d '{"target":"https://www.google.com/"}' http://localhost:8001/api/routes/goo/`
3) Tried to access the newly defined route: Opened chrome and navigated to http:/localhost:8000/goo

I then received a 404 error from google with the message "The requested URL /goo was not found on this server."

That was not the behaviour that I expected - I expected that the internal URL /goo was not transmitted to the target (which I was able to fix by adding the --no-include-prefix option) and also that all responses from the target would be parsed to "fix" all www.google.com or / URIs with the prefix /goo I just created, thus making this into a full-featured reverse proxy, but looking at the code returned by CHP all original URIs are untouched (this I could not fix at all).

Am I doing anything wrong or it is not possible to use CHP as a real reverse proxy?

Regards,
/Edson

**Comment by minrk** [comment]
You are right that CHP doesn't rewrite URLs, so requesting `/goo/` will request `https://www.google.com/goo/`.

**Comment by willingc** [comment]
Hi @ecarlotti,

Closing this issue since it appears to be resolved. Please leave a comment requesting this issue be reopened if you are still experiencing the issue. Thanks to all!
