### ISSUE TITLE
Different behavior from proxy targets

### ISSUE THREAD

**Issue by archman** [jupyterhub/configurable-http-proxy#135]
Hello,

## Test with google.com
I tried to proxy to www.google.com: `configurable-http-proxy --insecure --log-level debug --default-target https://www.google.com/`, the log shows proxy rule is created:
    
    12:09:54.249 - warn: [ConfigProxy] REST API is not authenticated.
    12:09:54.253 - info: [ConfigProxy] Adding route / -> https://www.google.com/
    12:09:54.258 - info: [ConfigProxy] Proxying http://*:8000 to https://www.google.com/
    12:09:54.259 - info: [ConfigProxy] Proxy API at http://localhost:8001/api/routes

But I cannot reach google from `http://127.0.0.1:8000`, after waiting for a while, looks like it was trying to reach `https://www.google.com:8000/`.

## Test with simple Flask application
I built a simple web service with Python, e.g.:
```python
from flask import Flask


app = Flask(__name__)

@app.route('/')
def index():
    return "Hello"

if __name__ == '__main__':
    app.run(port=5002)
```
I can proxy it with `configurable-http-proxy --default-target http://127.0.0.1:5002`

## Test with more complex Flask application
I changed the default target with another URL, e.g. `http://127.0.0.1:5050`, which is built by myself for other purpose, of course I can reach with `http://127.0.0.1:5050`, but I cannot reach it from `http://127.0.0.1:8000`, the target service log shows not found:

`127.0.0.1 - - [08/Nov/2017 12:21:59] "GET / HTTP/1.1" 404 -`

So, now I'm confused, I assume the above three cases should be the same, but just with different results.

Any follow up is appreciated!

-Tong

**Comment by archman** [comment]
Just figured out the reason why I cannot reach my flask applications, because I fixed the host address in my flask application configuration (solution is to change `127.0.0.1:5050` to be `0.0.0.0:5050` in configuration file), the proxied target by CHP might be different even though they are the same string (`http://127.0.0.1:5050`).

However, still I cannot correctly proxy website like google.com, i.e. the first section of this issue ticket.

**Comment by archman** [comment]
Huh, I think I found the reason, here is the result from `curl -X GET http://127.0.0.1:8000`:
```
<HTML><HEAD><meta http-equiv="content-type" content="text/html;charset=utf-8">
<TITLE>301 Moved</TITLE></HEAD><BODY>
<H1>301 Moved</H1>
The document has moved
<A HREF="http://www.google.com:8000/">here</A>.
</BODY></HTML>
```
I guess google does not allow `--insecure` option, so just showed `301`.

**Comment by minrk** [comment]
CHP looks to be proxying the initial request properly. The upstream google server, upon completion of that request, is choosing to redirect. Given that it's redirecting to port 8000, my guess is that the redirect is based on the proxied Host header or some other header identifying the host that the browser has requested. I'm not sure *why* Google is doing that, but that's Google's choice.
