### ISSUE TITLE
Persistent storage

### ISSUE THREAD

**Issue by nmarcetic** [jupyterhub/configurable-http-proxy#138]
Hey folks, I have a question about routing table storing. I saw that default store class is in memory and I can pass a storage, 

```--storage-backend <storage-class>  Use for custom storage classes``` What this actually means :) And whats the storage-class. My question is there any way to use persistent storage such as redis or anything, because I don't want to use in memory storage, will lose  my routing table on service restart :) right ?

Thanks!

**Comment by minrk** [comment]
A new feature! cc @jonathansp who implemented the feature. A redis backend: https://github.com/globocom/configurable-http-proxy-redis-backend

**Comment by jonathansp** [comment]
Hi @nmarcetic, as @minrk mentioned, it is a feature that allows you to save your routing table in a Redis server. We are already using in our production environment. Basically, install the extension:

 `npm install configurable-http-proxy-redis-backend`

export your Redis URI:

`export CONFIGURABLE_PROXY_REDIS_URI=redis://host.myredis:6379``

And add --storage-backend to proxy parameters:

`    --storage-backend configurable-http-proxy-redis-backend`

Please let me know if something is wrong. Also, you can create an issue in[ our repository.](https://github.com/globocom/configurable-http-proxy-redis-backend)

@minrk, I believe this issue can be closed.

**Comment by minrk** [comment]
@jonathansp thanks!

**Comment by SMHari** [comment]
@jonathansp how can this be extended to use if I'm running CHP separately as a pod from the hub?

**Comment by minrk** [comment]
@SMHari in this comment just above: https://github.com/jupyterhub/configurable-http-proxy/issues/138#issuecomment-372114172

**Comment by SMHari** [comment]
Hi @minrk 
Thanks for your reply

But the part I can't understand is, where this configurable-HTTP-proxy-Redis-backend needs to be installed and configured.
Is it in the jupyterhub itself? 
since we are running the CHP proxy as a separate service and using the CHP image for the same.

The comment posted above discusses, installing the package but not specifies exactly whether that needs to be installed if using a separate proxy

**Comment by jonathansp** [comment]
Hi @minrk 

_configurable-http-proxy-redis-backend_ must be installed in the same place (node-modules, docker image etc) you installed _configurable-http-proxy_. It's not a separate service; it is an extension that allows the use of Redis.

**Comment by SMHari** [comment]
Gotcha
Thanks, @jonathansp 🙌🏻
