### ISSUE TITLE
proxy hold many died died connections

### ISSUE THREAD

**Issue by forbxy** [jupyterhub/configurable-http-proxy#139]
proxy hold many died connections,which didn't existed in notebook or nginx,。
![bug](https://user-images.githubusercontent.com/8939700/34207889-3f9d733c-e5c7-11e7-83e1-c9758df8a559.png)
like this，connection's dest notebook have already drop it, but CHP  hold those connections forever

**Comment by willingc** [comment]
Hi @forbxy, Are you still seeing this issue or can it be closed? Thanks.

**Comment by forbxy** [comment]
We are upgrading notebook ,CHP, jupyterhub now,I will test if it still happen when we finish those upgraded

**Comment by willingc** [comment]
@forbxy I'm doing a bit of issue gardening. Is this still an issue if using CHP v3.1.1? Or can this be closed? Thanks!

**Comment by forbxy** [comment]
we upgrade system to ubuntu16.04,and run CHP on a k8s pod,and CHP ESTABLISH link go ok,but the CLOSE_WAIT status link is growing, it  it don't happend on your server?I think it is easy to reproduct,Just count the link which command netstat -a

**Comment by lzfxxx** [comment]
Do you still have this issue? If not, could you share the solution?

**Comment by forbxy** [comment]
Open it by the next user with this question.
