### ISSUE TITLE
Prepare minor release 3.1.1

### ISSUE THREAD

**Issue by willingc** [jupyterhub/configurable-http-proxy#145]
Create a release for recent changes:

- [ ] Node js v8 support landing in conda-forge ([PR](https://github.com/conda-forge/configurable-http-proxy-feedstock/pull/15)
- [x] update changelog (#147)

**Comment by minrk** [comment]
I think this will be 3.1.1, since #144 is the only real change.

> Node js v8 support landing in conda-forge

This isn't related to the configurable-http-proxy version. It's purely a conda-forge packaging question. The past several releases of CHP should already work fine on node 8 and 9.

**Comment by minrk** [comment]
Released 3.1.1
