### ISSUE TITLE
[Help] Recommended configuration for production deployment

### ISSUE THREAD

**Issue by akhilputhiry** [jupyterhub/configurable-http-proxy#182]
Loading `jupyter` via `configurable-http-proxy` takes 25seconds.
Is there some way we can speed this up via some configurations?

I am running proxy on `200m` CPU and `512Mi` RAM

**Comment by akhilputhiry** [comment]
@minrk Any thoughts?

**Comment by minrk** [comment]
Sorry, this isn't nearly enough information to have any thoughts. Can you provide a lot more details? Is this all on one machine? Are you using docker? How are you adding routes to CHP? What version of Python, node, notebook, and CHP? Is this JupyterHub, or a standalone notebook server? Are you accessing via localhost, local network, or public internet?

Normally, this is on the order of milliseconds with defaults everywhere, so I would guess that either:

1. this is including process startup time for the notebook server (that's still quite slow, but on very slow VMs, it can take a while), or
2. there is some DNS resolution that's timing out. That's usually my first place to look for timeouts of 20-30 seconds

**Comment by akhilputhiry** [comment]
@minrk Please find the details below

Is this all on one machine?
I am running this on a k8 cluster

How are you adding routes to CHP?
I am using it along with jupyterhub

What version of Python, node, notebook, and CHP? 
Python - 3.6
Node - 6.12.3
CHP - 3.1.1

Is this JupyterHub, or a standalone notebook server?
yes. It is JupyterHub

Are you accessing via localhost, local network, or public internet?
Public internet

**Comment by minrk** [comment]
What is taking 25 seconds? Is this the total time to launch a user's server, or is it the time to load an already running and ready server?

**Comment by consideRatio** [comment]
This may have been slow on k8s due to:
- readinessProbe configuration not making the pod to be considered ready quickly even though it is started up - this is improved in z2jh's helm chart that relies on this to have a startup speed of ~1-3 seconds or so.
- imagePullPolicy configuration forcing repulls of the image

I'll go ahead and close this as outdated for now.
