### ISSUE TITLE
configurable-http-proxy -h  Problems,may about es6

### ISSUE THREAD

**Issue by ch-liuzhide** [jupyterhub/configurable-http-proxy#199]
![image](https://user-images.githubusercontent.com/44251801/54268481-3d84f980-45b6-11e9-9a3e-02f0fdc3949f.png)

why this happen?  I try to delete  the {},then 
![image](https://user-images.githubusercontent.com/44251801/54268556-6dcc9800-45b6-11e9-9705-29fd7d06b112.png)
 
I guess something wrong about this package.

**Comment by minrk** [comment]
What do you get from `npm version`?

**Comment by consideRatio** [comment]
Closing this as we have bumped the version of winston since this error occurred, and I could not reproduce this error.
