### ISSUE TITLE
Making a release

### ISSUE THREAD

**Issue by consideRatio** [jupyterhub/configurable-http-proxy#219]
I'd be very happy to see a release of CHP for z2jh to use. It would allow the z2jh proxy pod to snappily restart following #217 and also allowing the hub pod to become ready a lot quicker without erroring. The hub pod will crash with error unless it has successfully communicated with a running proxy pod that is slow to restart for example.

I'd happily put in some effort here, but could use some initial guidance, approval to work toward making a release, and considerations to have in mind etc.

**Comment by minrk** [comment]
Let's add it! Releasing CHP is the same as ~any npm package:

```bash
npm version $VERSION
npm publish
git push --tags
```

You need an npm account and I can give you access.

**Comment by consideRatio** [comment]
Deal okay I'll learn about that then, I have no experienced on that ;)

Push a git tag, build and pusha a docker image, build and publish the npm package. @minrk I created an account called `consideratio` on npmjs.

I note that the `:latest` docker image tag on [dockerhub](https://hub.docker.com/r/jupyterhub/configurable-http-proxy/tags?page=1&ordering=last_updated) was updated, but the Docker image tag 4.1.0 was pushed 7 months ago.

**Comment by minrk** [comment]
Docker images are tagged and built automatically on docker hub, so should be no need to do anything there. I think those three lines are literally everything in making a release, assuming changelog, etc. are up to date. I've given you write access to the package on npm, so you should be able to publish the next release!

**Comment by consideRatio** [comment]
A release is made now! :)

**Comment by minrk** [comment]
Excellent, thank you!
