### ISSUE TITLE
A / A+ TLS termination config by default for CHP

### ISSUE THREAD

**Issue by zmkhazi** [jupyterhub/configurable-http-proxy#287]
Hello JupyterHub Experts:

I have the JupyrterHub deployment on Docker Swarm on Linux. The JupyterHub docker image is pushed on the local registry listening on port 5000.  Besides, JupyterHub image there isn't any other image on this repo. 

The following are the configuration entries in the Jupterhub config file.  Desipte of explicitly setting it to TLSv.2, the TLSv1.0 and TLSv1.1 are still being present and getting flagged in the scan.  How do I overcome this ? The intent here is to only have TLSv1.2 not the older versions. 

c.ConfigurableHTTPProxy.command = ['configurable-http-proxy', '--ssl-protocol', 'TLSv1.2']
c.JupyterHub.proxy_cmd = ['configurable-http-proxy', '--ssl-protocol=TLSv1.2']

**"The following is an extract from the TLS Scan Report"**

  TLSv1.0:
     server selection: enforce server preferences
     3f- (key:  RSA)  ECDHE_RSA_WITH_AES_128_CBC_SHA
     3f- (key:  RSA)  ECDHE_RSA_WITH_AES_256_CBC_SHA
     3-- (key:  RSA)  RSA_WITH_AES_128_CBC_SHA
     3-- (key:  RSA)  RSA_WITH_AES_256_CBC_SHA
  TLSv1.1: idem
  TLSv1.2:
     server selection: enforce server preferences
     3f- (key:  RSA)  ECDHE_RSA_WITH_AES_128_GCM_SHA256
     3f- (key:  RSA)  ECDHE_RSA_WITH_AES_128_CBC_SHA
     3f- (key:  RSA)  ECDHE_RSA_WITH_AES_256_CBC_SHA
     3-- (key:  RSA)  RSA_WITH_AES_128_CBC_SHA
     3-- (key:  RSA)  RSA_WITH_AES_256_CBC_SHA

**Comment by manics** [comment]
Using an external website to check your HTTPS setup is the easiest, but you can also test it yourself using `openssl s_client` or `nmap`:
https://security.stackexchange.com/questions/70733/how-do-i-use-openssl-s-client-to-test-for-absence-of-sslv3-support

**Comment by atnjqt** [comment]
Thanks for the note, @manics. The problem is not my ability to test our SSL configurations, Qualys SSLLabs is a great tool for checking public facing hosts. I might explore the nmap & openssl tests as you mentioned, but that does not solve my issue of passing configurable-http-proxy configs via the Jupyterhub Configuration file!

**Comment by consideRatio** [comment]
@atnjqt note that our priorities may differ a bit :) Your priority may be to solve the issue for yourself where a workaround is considered a solution, while my maintainer priority is first and foremost to not have anyone need to workaround in the future.

The quick solution for you if you want to workaround this current limitation in configurable-http-proxy used by JupyterHub, is probably to setup another proxy to do the TLS termination in a satisfactory manner before it reaches JupyterHub and the configurable-http-proxy that JupyterHub use of to dynamically route traffic to user servers.

**Comment by consideRatio** [comment]
Perhaps we should update our cipher suite that is accepted? It seems like configurable-http-proxy relies on http-proxy, which relies on node's base libraries to do the TLS parts.

Mozilla has this nice website with recommendations of ciphers for various web servers and that is what we decided to use in the JupyterHub Helm chart's TLS termination done in Traefik:
https://ssl-config.mozilla.org/#server=traefik&version=2.1.2&config=intermediate&guideline=5.6

https://github.com/jupyterhub/configurable-http-proxy/blob/7f04842ee2a120f7335c6555a866e33787f89887/bin/configurable-http-proxy#L136-L160

**Comment by atnjqt** [comment]
@consideRatio thanks for the note, my apologies as I did not mean to suggest my organization's priorities are the same as the jhub maintainers! But yes it certainly would be nice if there was someway to harden the configurable-http-proxy via JupyterHub configuration script!

**Comment by manics** [comment]
I haven't tested this, but examining the code:
https://github.com/jupyterhub/configurable-http-proxy/blob/292b7924c19556af8578fecae282ca26409fe072/bin/configurable-http-proxy#L182
takes the `--ssl-protocol` argument and appends `_method`

I'm guessing this might refer to something in the [`tls` library](https://nodejs.org/api/tls.html) which says
> secureProtocol <string> Legacy mechanism to select the TLS protocol version to use, it does not support independent control of the minimum and maximum version, and does not support limiting the protocol to TLSv1.3. Use minVersion and maxVersion instead. The possible values are listed as SSL_METHODS, use the function names as strings. For example, use 'TLSv1_1_method' to force TLS version 1.1, or 'TLS_method' to allow any TLS protocol version up to TLSv1.3. It is not recommended to use TLS versions less than 1.2, but it may be required for interoperability. Default: none, see minVersion.

and links to https://www.openssl.org/docs/man1.1.1/man7/ssl.html#Dealing-with-Protocol-Methods

So maybe `TLSv1_2` will work?
Though we should refactor this since it's not obvious, and also doesn't support TLS 1.3

**Comment by minrk** [comment]
Closing as a duplicate of #279 which has an example of specifying ciphers for an A grade and tls version:

```python
c.ConfigurableHTTPProxy.command = ['configurable-http-proxy', '--ssl-version=TLSv1_2', '--ssl-ciphers=ECDHE-RSA-AES128-GCM-SHA256,ECDHE-ECDSA-AES128-GCM-SHA256,ECDHE-RSA-AES256-GCM-SHA384,ECDHE-ECDSA-AES256-GCM-SHA384,DHE-RSA-AES128-GCM-SHA256,ECDHE-RSA-AES128-SHA256,DHE-RSA-AES128-SHA256,ECDHE-RSA-AES256-SHA384,DHE-RSA-AES256-SHA384,ECDHE-RSA-AES256-SHA256,DHE-RSA-AES256-SHA256,HIGH,!aNULL,!eNULL,!EXPORT,!DES,!RC4,!MD5,!PSK,!SRP,!CAMELLIA']
```

though the defaults with a recent-enough node are also good enough to achieve this result
