### ISSUE TITLE
Unable to upload file >15MB on JupyterHub

### ISSUE THREAD

**Issue by oharach1** [jupyterhub/configurable-http-proxy#339]
Hi, I just installed JupyterHub into K8s environment and for some reason I am not able to upload large files (>15MB) via upload bottom on JupyterNotebook using classic view, I am getting an error net:ERR_CONNECTION_RESET

I am not using nginx as reverse proxy, the setup is based on configurable-http-proxy to manage the spawner process. I am not sure if there is a configuration parameter for configurable-http-proxy related to set a timeout or proxy_timeout in order to give more time before the connection is reset.

I will appreciated any help for this.

Thanks,

**Comment by manics** [comment]
It looks like you've already found https://github.com/jupyterhub/configurable-http-proxy/issues/311 so I'll close this.
