### ISSUE TITLE
Add custom-header failed

### ISSUE THREAD

**Issue by alexk1028** [jupyterhub/configurable-http-proxy#396]
### Bug description

add a header failed, but i don't know why it happend

#### Expected behaviour

create user server success and response header exist 

#### Actual behaviour

start chp failed

### How to reproduce

1. config.yaml 
proxy:
  service:
    type: NodePort
    nodePorts:
      http: 32084
  chp:
    extraCommandLineFlags: ["--custom-header=frame-ancestors192.168.74.169:32080"]
2. upgrade by helm
3. See error

### Your personal set up

k8s: v1.20.11

 - OS: ubuntu 20.04
 - Version(s): 4.5.0

**Comment by consideRatio** [comment]
@alexk1028 start by using version 4.5.1, note how the changelog includes a relevant bugfix: https://github.com/jupyterhub/configurable-http-proxy/blob/main/CHANGELOG.md#451---2022-02-02. To use a more modern version via the jupyterhub helm chart, you can probably update the value `proxy.chp.image.tag` to reference a more modern version.

If you can reproduce it still, please also provide details on the failure beyond `start chp failed`. What are the logs etc? (`kubectl logs deploy/proxy`).
