### ISSUE TITLE
Update to use alpine 3.16 as a base image.

### ISSUE THREAD

**Issue by Christian-Nunnally** [jupyterhub/configurable-http-proxy#415]
### Proposed change

Alpine 3.15 has some CVE violations and should be updated to 3.16.

### Who would use this feature?

Everyone.

### (Optional): Suggest a solution

I tried to create a PR to make this small change but so not have permission in the repository. Also the contributing.MD does not exist.

**Comment by consideRatio** [comment]
@Christian-Nunnally hi! Feel free to open a PR using a branch in a "fork" of this project. You are now allowed to create branches in this github repository, but you are allowed to make a copy of it and create a pull request to your copied projects branch!

I think this guide may help with those steps: https://opensource.com/article/19/7/create-pull-request-github

Cheers!

**Comment by Christian-Nunnally** [comment]
@consideRatio Thank you! I was able to create a PR here: https://github.com/jupyterhub/configurable-http-proxy/pull/416

**Comment by consideRatio** [comment]
Closed by #416 - thanks @Christian-Nunnally!!!

Btw, if your PR description includes "closes #416" or "fixes #416", github will automatically close that associated issue when the PR is merged :)

Thanks for your contribution!!! :heart: :tada: :sunflower: You can now use version 4.5.2 of the image.
