### ISSUE TITLE
Define a standard, reproducible way to load test CHP

### ISSUE THREAD

**Issue by yuvipanda** [jupyterhub/configurable-http-proxy#49]
Knowing the amount of load / routes that CHP can handle is important when doing large deployments of JupyterHub. Having a standard and easy way to load test this would be very useful. There are a bunch of factors that should be measured:
1. Number of route definitions in place
2. Number of open websocket connections
3. Rate of activity over the websocket connections
4. Rate of regular http requests proxied

**Comment by minrk** [comment]
Yup, that would be great.

**Comment by yuvipanda** [comment]
I took a stab at this today, kindof. I experimented with setting up a selenium test that will pretend to be a normal human being and do normal human things to the notebooks, and got it to work with a hello world setup - and *then* I found out that notebook already uses casperjs for similar testing. So I'll start looking into that and see how you can run massively parallel tests against jupyterhub with selenium/casperjs.

I also looked into the Gatling project, but somehow doing load testing via those projects seems less... accurate.

**Comment by rgbkrk** [comment]
You may want to try out something with Electron, even headless, for running tests like that. Casper and phantom only lead to pain.

**Comment by yuvipanda** [comment]
Oh, I see. I haven't used Casper/phantom before, and a google search for
'phantomjs sucks' doesn't turn up anything useful :D can you tell me some
more about the kinds of pain it leads to?

**Comment by yuvipanda** [comment]
There is also a phantomjs driver for selenium, so perhaps it is OK to
continue down this path (that is, using selenium). This allows me to keep
the tests in Python, which I prefer. Could also use selenium grid to do the
load testing.

**Comment by rgbkrk** [comment]
~~PhantomJS is on an old version of WebKit and version 2 of Phantom JS has stalled~~

Nevermind me, seems development picked back up and they're not on a way too old version of WebKit anymore, having [made a release a couple weeks ago](https://twitter.com/AriyaHidayat/status/691032260728893440).

**Comment by rgbkrk** [comment]
Yup, seems like you're covered.

**Comment by yuvipanda** [comment]
Ok, so here's my current plan:

1. Write a selenium script that can replay arbitrary ipynb files in human feeling ways (actually typing out the code, ocassional tab completions and re-executions, etc)
2. Build a corpus of such notebooks (probably pick some real world ones!)
3. Setup a selenium grid to do the actual load testing

We can vary the rate of activity by varying the corpus of notebooks, and the number of users by scaling the selenium grid. This not only tests the webproxy but everything, end to end - will make it clear what the bottlenecks are :)

Given that it's no longer testing the proxy alone, I'm wondering if we should move this issue to another repo. And perhaps, we should have a thing that just tests the proxy using a more performance testing oriented setup.

**Comment by minrk** [comment]
If you want to do performance testing of the notebook, that's great and useful, but I don't think it necessarily precludes doing a simpler benchmark of the proxy itself, which should be more easily done with dummy backends. Knobs I see:

- http requests
  - concurrent requests
  - request/reply size
- websockets
  - concurrent connections
  - message frequency
  - message size
- number of backends

I think it's fine to continue to discuss the notebook benchmark task here.

**Comment by yuvipanda** [comment]
Yeah, I agree that these are two orthogonal cases that should be handled separately by different tools, and are both useful.

**Comment by minrk** [comment]
@GeorgianaElena did some [great benchmarking](https://nbviewer.jupyter.org/github/jupyterhub/traefik-proxy/blob/master/performance/ProxyPerformance.ipynb) as part of developing the traefik proxy. I think we can close this.
