### ISSUE TITLE
EKS container pods unable to communicate with proxy

### ISSUE THREAD

**Issue by bbry89** [jupyterhub/configurable-http-proxy#501]
### Bug description

I have [z2jh](https://z2jh.jupyter.org/en/stable/) set up on AWS EKS using configurable-http-proxy as the proxy. Recently, I have seen jupyterhub being slow to load and then failing with ERR_EMPTY_RESPONSE message after a few minutes of attempting to load. If jupyterhub does get loaded, it will pop up a message with "Server unavailable or unreachable" after just a few minutes. At this point, Jupyter will not respond to any operations or commands given.

I have seen failures in the browser console with the same ERR_EMPTY_RESPONSE message in response to api calls: `https://host:port/user/username1/api/sessions?content=1&1695851658265`. However, `kubectl logs ...` and `kubectl describe pods ...` does not show any indications of errors from kubernetes side.

The only fix that I have found is to restart our proxy server, which is a kubernetes pod running configurable-http-proxy. Immediately after restarting, all issues seen with jupyterhub clients disappears.

### How to reproduce

The issues randomly occurs. I have not been able to track down what causes this issue to reproduce it.

#### Expected behaviour

Jupyter client should be able to connect to kubernetes pods without issues

#### Actual behaviour

All Jupyter client API calls fail with ERR_EMPTY_RESPONSE, rendering it completely unresponsive to any actions taken by a user until the proxy is restarted.

### Your personal set up

 - OS: Linux/UNIX EC2 instance
 
 - Version(s):
 

jupyterhub==3.1.0
jupyterlab==3.5.2
notebook==6.2.0
configurable-http-proxy==4.5.4
kubernetes==1.24

<details><summary>Full environment</summary>

```
# paste output of `pip freeze` or `conda list` here
```
</details>

<details><summary>Configuration</summary>

```python
# jupyterhub_config.py
```
</details>

<details><summary>Logs</summary>

```
# paste relevant logs here, if any
```
</details>

**Comment by manics** [comment]
This is likely to be a problem with your Kubernetes cluster, rather than a bug with JupyterHub/Z2JH/Configurable http proxy.

For example, I've seen problem related to the EKS networking plugin before. Unfortunately there's no easy solution, you may need to start debugging EKS at quite a low level. If you need more help your best option is to use the Jupyter community forum and see if anyone else has an idea https://discourse.jupyter.org/
