### ISSUE TITLE
Add prometheus based metrics

### ISSUE THREAD

**Issue by yuvipanda** [jupyterhub/configurable-http-proxy#52]
https://github.com/minrk/chpbench/issues/1#issuecomment-191405430 for rationale.

More things to add:
1. Counters for requests by response status code (and by ws vs web)
2. Timing info for each webrequest
3. Gauges for active websocket connections
4. Counters for REST API requests.

**Comment by yuvipanda** [comment]
I added code to collect metrics about the various response codes, but am not sure I see an easy way to get timing information for requests at all.

**Comment by minrk** [comment]
Retitled to prometheus, since we don't do statsd much anymore
