### ISSUE TITLE
noXHeaders -> noXForward ?

### ISSUE THREAD

**Issue by quasiben** [jupyterhub/configurable-http-proxy#68]
Should the argument or variable name change here ?
https://github.com/jupyterhub/configurable-http-proxy/blob/master/bin/configurable-http-proxy#L181

**Comment by rgbkrk** [comment]
How are people using this argument right now? What's this impacting?

**Comment by quasiben** [comment]
I am -- i'm trying to use `configurable-http-proxy` to proxy to bokeh apps. Previously, this argument was broken and `xfwd` was always set true.  And resulted in headers like the following:

> x-forwarded-proto=https, cf-visitor={"scheme":"https"}

which lead to a header on the bokeh side like the following:

> 'X-Forwarded-Proto': 'https,https'

I asked Tornado folks about stripping redundant (or picking the first option) and they said this wasn't build but could be.  In the mean time, I thought i could fix.  It looked like at one point `xHeader` was being used but then was switched to `xForward`?

**Comment by rgbkrk** [comment]
#15 is the originating PR, so @minrk would know best if changing the option (instead of adding this on as an additional) will be alright
