### ISSUE TITLE
Update warning message ip address

### ISSUE THREAD

**Issue by willingc** [jupyterhub/configurable-http-proxy#78]
In https://github.com/jupyterhub/configurable-http-proxy/blob/master/bin/configurable-http-proxy#L216, we caution against using '*' as an ip in the docs and in the warning a few lines above yet it is displayed by L216. Perhaps change to '0.0.0.0' or '' or emit a warning such a few lines above.

**Comment by minrk** [comment]
There's an ever-so-slight difference between `''` and `0.0.0.0`, where `''` is *all interfaces*, while `0.0.0.0` is *all IPv4 interfaces*. This will make a difference approximately never, but we could use the text "all interfaces" when ip is blank.
